name = "Collatz"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Collatz"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "Collatz"
